# Reverse Proxy
nginx:
  build: ./nginx
  ports:
    - "80:80"
  links:
    - kibana

# ElasticSearch Service
elasticsearch:
  build: ./elasticsearch
  ports:
    - "9200:9200"
    - "9300:9300"

# Kibana Service
kibana:
  build: ./kibana
  ports:
    - "5601:5601"
  links:
    - elasticsearch

# Logstash Service
logstash:
  build: ./logstash
  ports:
    - "5000:5000"
  links:
    - elasticsearch
    - redis

# Redis broker
redis:
  build: ./redis
  ports:
    - "6379:6379"