# Set nginx base image
FROM elasticsearch:latest

# File Author / Maintainer
MAINTAINER Marcin Mrotek

# Copy custom configuration file from the current directory
# COPY elasticsearch.yml /usr/share/elasticsearch/config